In [4]:
#1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

#Створюємо одновимірний масив (вектор) з першими 10-ма натуральними числами
natural_numbers = list(range(1, 11))

# Виводимо значення масива
natural_numbers 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
#2.Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення
import numpy as np

# Створюємо двовимірний масив (матрицю) розміром 4x4, заповнений одиницями
matrix_4x4 = np.ones((4, 4))

# Виводимо значення матриці
print(matrix_4x4)
    

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
#3.Створіть масив розміром 4x4, заповніть його випадковими цілими числами в діапазоні від 1 до 5 та виведіть його значення.

import numpy as np

# Створюємо масив 4x4 з випадковими числами від 1 до 5
array = np.random.randint(1, 6, size=(4, 4))

# Виводимо масив
print(array)


[[4 5 3 1]
 [2 5 5 3]
 [4 2 1 3]
 [2 1 2 4]]


In [7]:
#4.Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
import numpy as np

# Створюємо масив 3x3 з випадковими дійсними числами від 0 до 1
array = np.random.random((3, 3))

# Виводимо масив
print(array)


[[0.92461883 0.13789505 0.22146148]
 [0.17746231 0.95159861 0.00969123]
 [0.32896112 0.56348099 0.92285816]]


In [8]:
#5.Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

import numpy as np

# Створюємо два масиви розміром 6 з випадковими цілими числами від 1 до 20
array1 = np.random.randint(1, 21, size=6)
array2 = np.random.randint(1, 21, size=6)

# Виводимо масиви
print("Array 1:", array1)
print("Array 2:", array2)

# Виконуємо поелементні операції
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Виводимо результати операцій
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)


Array 1: [17 20 18  1  5 14]
Array 2: [ 8  7  3 14  9 20]
Addition: [25 27 21 15 14 34]
Subtraction: [  9  13  15 -13  -4  -6]
Multiplication: [136 140  54  14  45 280]


In [9]:
#6.Створіть два матриці 2x2, заповніть їх довільними цілими числами та знайдіть їх добуток.

import numpy as np

# Створюємо дві матриці 2x2 з випадковими цілими числами
matrix1 = np.random.randint(1, 10, size=(2, 2))
matrix2 = np.random.randint(1, 10, size=(2, 2))

# Виводимо матриці
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Обчислюємо добуток матриць
product = np.dot(matrix1, matrix2)

# Виводимо добуток
print("Product of Matrix 1 and Matrix 2:\n", product)


Matrix 1:
 [[4 5]
 [4 7]]
Matrix 2:
 [[1 7]
 [3 6]]
Product of Matrix 1 and Matrix 2:
 [[19 58]
 [25 70]]


In [10]:
#7.Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

import numpy as np

# Створюємо першу матрицю розміром 3x2 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(3, 2))

# Створюємо другу матрицю розміром 2x4 з випадковими цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, size=(2, 4))

# Виводимо матриці
print("Matrix 1 (3x2):\n", matrix1)
print("Matrix 2 (2x4):\n", matrix2)

# Обчислюємо добуток матриць
product = np.dot(matrix1, matrix2)

# Виводимо добуток
print("Product of Matrix 1 and Matrix 2:\n", product)


Matrix 1 (3x2):
 [[8 2]
 [1 4]
 [5 4]]
Matrix 2 (2x4):
 [[ 3  7  6  8]
 [ 1  7 10  2]]
Product of Matrix 1 and Matrix 2:
 [[26 70 68 68]
 [ 7 35 46 16]
 [19 63 70 48]]


In [11]:
#8.Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю.

import numpy as np

# Створюємо матрицю 2x2 з випадковими цілими числами від 1 до 7
matrix = np.random.randint(1, 8, size=(2, 2))

# Виводимо матрицю
print("Matrix:\n", matrix)

# Обчислюємо обернену матрицю
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("Inverse Matrix:\n", inverse_matrix)
except np.linalg.LinAlgError:
    print("Матриця не має оберненої, оскільки є сингулярною.")


Matrix:
 [[2 5]
 [7 5]]
Inverse Matrix:
 [[-0.2   0.2 ]
 [ 0.28 -0.08]]


In [12]:
#9.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

import numpy as np

# Створюємо матрицю 3x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.random((3, 3))

# Виводимо матрицю
print("Original Matrix:\n", matrix)

# Транспонуємо матрицю
transposed_matrix = np.transpose(matrix)

# Виводимо транспоновану матрицю
print("Transposed Matrix:\n", transposed_matrix)


Original Matrix:
 [[0.31318875 0.45310625 0.93505316]
 [0.46402356 0.02203795 0.57982736]
 [0.34783983 0.97328567 0.72531706]]
Transposed Matrix:
 [[0.31318875 0.46402356 0.34783983]
 [0.45310625 0.02203795 0.97328567]
 [0.93505316 0.57982736 0.72531706]]


In [13]:
#10.Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток матриці на вектор.

import numpy as np

# Створюємо матрицю 3x4 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 4))

# Створюємо вектор 4x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(4, 1))

# Виводимо матрицю та вектор
print("Matrix (3x4):\n", matrix)
print("Vector (4x1):\n", vector)

# Обчислюємо добуток матриці на вектор
product = np.dot(matrix, vector)

# Виводимо добуток
print("Product of Matrix and Vector:\n", product)


Matrix (3x4):
 [[9 4 3 4]
 [6 5 2 4]
 [9 2 1 5]]
Vector (4x1):
 [[7]
 [8]
 [5]
 [8]]
Product of Matrix and Vector:
 [[142]
 [124]
 [124]]


In [14]:
#11.Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

import numpy as np

# Створюємо матрицю 2x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(2, 3))

# Створюємо вектор 3x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(3, 1))

# Виводимо матрицю та вектор
print("Matrix (2x3):\n", matrix)
print("Vector (3x1):\n", vector)

# Обчислюємо добуток матриці на вектор
product = np.dot(matrix, vector)

# Виводимо добуток
print("Product of Matrix and Vector:\n", product)



Matrix (2x3):
 [[4 7 4]
 [3 8 6]]
Vector (3x1):
 [[4]
 [5]
 [1]]
Product of Matrix and Vector:
 [[55]
 [58]]


In [15]:
#12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму

import numpy as np

# Створюємо першу матрицю розміром 2x2 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))

# Створюємо другу матрицю розміром 2x2 з випадковими цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Виводимо матриці
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Обчислюємо суму матриць
sum_matrix = matrix1 + matrix2

# Виводимо суму
print("Sum of Matrix 1 and Matrix 2:\n", sum_matrix)


Matrix 1:
 [[2 5]
 [2 3]]
Matrix 2:
 [[5 2]
 [3 8]]
Sum of Matrix 1 and Matrix 2:
 [[ 7  7]
 [ 5 11]]


In [16]:
#13.Створіть дві матриці розміром 2x2, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть їх добуток.

import numpy as np

# Створюємо першу матрицю розміром 2x2 з випадковими дійсними числами від 0 до 1
matrix1 = np.random.random((2, 2))

# Створюємо другу матрицю розміром 2x2 з випадковими дійсними числами від 0 до 1
matrix2 = np.random.random((2, 2))

# Виводимо матриці
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Обчислюємо добуток матриць
product = np.dot(matrix1, matrix2)

# Виводимо добуток
print("Product of Matrix 1 and Matrix 2:\n", product)


Matrix 1:
 [[0.65887921 0.21373296]
 [0.2085719  0.08723376]]
Matrix 2:
 [[0.81444386 0.97084773]
 [0.98077503 0.04880358]]
Product of Matrix 1 and Matrix 2:
 [[0.74624407 0.65010231]
 [0.2554268  0.20674888]]


In [17]:
#14.Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть суму елементів матриці

import numpy as np

# Створюємо матрицю 5x5 з випадковими дійсними числами від 0 до 1
matrix = np.random.random((5, 5))

# Виводимо матрицю
print("Matrix (5x5):\n", matrix)

# Обчислюємо суму всіх елементів матриці
sum_elements = np.sum(matrix)

# Виводимо суму
print("Sum of all elements in the matrix:", sum_elements)


Matrix (5x5):
 [[0.5029392  0.33553243 0.12312758 0.13690131 0.49808474]
 [0.68025637 0.43365541 0.71728423 0.18078768 0.53160633]
 [0.91849994 0.45477884 0.28105406 0.32548769 0.39879652]
 [0.65025974 0.79352448 0.73586495 0.78457047 0.85692558]
 [0.80080318 0.85291605 0.22437337 0.97946051 0.2545948 ]]
Sum of all elements in the matrix: 13.452085456291561


In [18]:
#15.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

import numpy as np

# Створюємо матрицю 3x3 з випадковими дійсними числами від -1 до 1
matrix = np.random.uniform(-1, 1, size=(3, 3))

# Виводимо матрицю
print("Matrix (3x3):\n", matrix)

# Обчислюємо суму елементів кожного рядка
row_sums = np.sum(matrix, axis=1)

# Перетворюємо вектор рядкових сум у стовпчик
row_sums_column_vector = row_sums.reshape(-1, 1)

# Виводимо вектор-стовпчик
print("Column vector with the sum of each row:\n", row_sums_column_vector)


Matrix (3x3):
 [[-0.65539641  0.35054521 -0.14592206]
 [-0.04237317  0.27618821 -0.30777192]
 [-0.37932096 -0.71290144  0.00515731]]
Column vector with the sum of each row:
 [[-0.45077326]
 [-0.07395689]
 [-1.08706509]]


In [ ]:
#Висновок:
#У рамках виконаних завдань було продемонстровано основи роботи з матрицями і векторами, використовуючи бібліотеку NumPy в Python.

#Створення та обробка матриць: Ми навчились створювати матриці різних розмірів та заповнювати їх випадковими дійсними і цілими числами в заданих діапазонах. Ці навички є базовими для роботи з числовими даними та виконанням математичних операцій.

#Матричні операції: Виконані операції включали:

#Добуток матриць: Ми навчились множити матриці, що демонструє як обчислювати матричний добуток.

#Обернена матриця: Було показано, як обчислювати обернену матрицю і враховувати можливі проблеми з сингулярними матрицями.

#Сума елементів: Визначили, як обчислювати суму всіх елементів матриці, що корисно для загальних статистичних обчислень.

#Операції з векторами: Показано, як виконувати операції між матрицями та векторами, зокрема, як обчислювати добуток матриці на вектор та знаходити суму елементів кожного рядка матриці.

#Ці завдання підкреслюють важливість вміння ефективно працювати з матрицями та векторами в наукових розрахунках і обробці даних, а також розвивають навички виконання основних матричних операцій, що є критично важливими для аналізу даних, чисельних методів та інших областей математики і науки.